import React from 'react'
import { useGetUserByIdQuery} from '@/redux/product';
import Head from 'next/head';

const SingleUser = () => {
    const router = useRouter()
    const userId = router.query.id;
    const {data,isLoading,error} = useGetUserByIdQuery(userId)
  return (
    <>
     <Head>
        <title>{data?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.webp" />
      </Head>

      {error ? (
        <h1>error</h1>
    ) : isLoading ? (
        <h1>Loading</h1>
    ) : data ? (
        <div className="card_id">
            <div className="cardd_id">
            <img src={el.img} alt="" />
            <h3>{el.name}</h3>
            <h4>{el.price}</h4>
            <h4>{el.speed}</h4>
            </div>
        </div>
    ) : null}
    </>
  )
}

export default SingleUser