import React from 'react'
import s from '../styles/local.module.css'
import Head from 'next/head'
import Footer from '@/components/Footer'
import Link from 'next/link'
import { GrLinkNext } from "react-icons/gr";
import { SiBmw } from "react-icons/si";

const Local = () => {
    return (
        <>
            <Head>
                <title>BMW local</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.webp" />
            </Head>
            

          <div className={s.back}>
            <div className={s.bb1}>
            <SiBmw size={60} /> 
            <Link href={"/"} > <h1>Back to Home</h1></Link>
            </div>
            <Link href={"/"}  ><GrLinkNext  size={30} /></Link>
          </div>

            <div className={s.local_parent}>
            <div className={s.local} >
           <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d18472201.338129397!2d-89.99531810800006!3d39.67003560396124!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2s!4v1704011910883!5m2!1sru!2s" width={700} height={700} ></iframe>
            </div>
            <div className={s.local_left}>
                <h1>Choose  your local <br /> center</h1>
                <div className={s.j122}>
                <p>search by location</p>
                <input type="text" placeholder='ZIP or City/State' />
                </div>
                 <p>or -</p>
                 <div className={s.j2344}>
                 <p>Search by dealer name</p>
                 <input type="text" placeholder='e.g. BMW of  Manhattan' /> 
                 </div>
                 <button>search</button>
            </div>
            </div>


             <Footer/>
        </>
    )
}

export default Local